NewMarket.Web/ViewModels/CategoryViewModels.cs
using NewMarket.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NewMarket.Web.ViewModels
{
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }

        public string SearchTerm { get; set; }
     
    }
    public class NewCategoryViewModels
    {
        [Required]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }
        public string ImageURL { get; set; }
        //public decimal Price { get; set; }
        
        public bool isFeatured { get; set; }
        //public int CategoryID { get; set; }
    }
    public class EditCategoryViewModels
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        //public decimal Price { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
        //public int CategoryID { get; set; }
    }
}

NewMarket.Web/Controllers/CategoryController.cs
using NewMarket.Entities;
using NewMarket.Services;
using System;
using NewMarket.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    //[Authorize(Roles ="Admin,Manager")]
    public class CategoryController : Controller
    {
        //CategoriesServices cs = new CategoriesServices();
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CategoryTable()
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            
            model.Categories = CategoriesServices.Instance.GetCategories();

            /*var categories = CategoriesServices.Instance.GetCategories();
            
            if (string.IsNullOrEmpty(search) == false)
            {
                categories = categories.Where(c => c.Name != null && c.Name.ToLower().Contains(search.ToLower())).ToList();
                categories = categories.Where(c => c.Name.Contains(search)).ToList(); 
            }*/
            return PartialView("CategoryTable", model);
        }

        public ActionResult CategorySearch(string search)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;

            var totalRecords = CategoriesServices.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesServices.Instance.GetCategoriesSearch(search);

            return PartialView("CategoryTable", model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            NewCategoryViewModels model = new NewCategoryViewModels();
            //var categories = CategoriesServices.Instance.GetCategories();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModels model)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesServices.Instance.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
 
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModels model = new EditCategoryViewModels();
            var category = CategoriesServices.Instance.GetCategory(ID);

            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Edit(EditCategoryViewModels model)
        {
            var existingCategory = CategoriesServices.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;

            CategoriesServices.Instance.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }

        
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            CategoriesServices.Instance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }
        
    }
}

NewMarket.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}",fileName) };

                //result.Data=new { Success=true,Image =fileName,File=newImage.ID,ImageURL=string.Format()}

            } catch (Exception e)
            {
                result.Data = new { Success = false, Message = e.Message };
            }

            return result;
        }
    }
}

NewMarket.Web/Views/Category/CategoryTable.cshtml
@model NewMarket.Web.ViewModels.CategorySearchViewModel
@{
    ViewBag.Title = "CategoryTable";
}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

<script src="~/Content/javascript/jquery.cookie.js"></script>
<script src="~/Content/javascript/main.js"></script>
<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Izlash</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Amallar</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="searchBtn">Izlash</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Yangilash</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newBtn">Yangi</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table id="CategoryTable" class="table table-striped" width="100%">
        <thead>
            <tr>
                <th class="font-weight-bold">Savdo markazi nomi </th>
                <th class="font-weight-bold">Ta'rif</th>
                <th class="font-weight-bold wrap-td">Amallar</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td width="30%">@category.Name</td>
                        <td width="44%">
                            @category.Description
                        </td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@category.ID">O'zgartirish</button>
                            <button class="deleteBtn" data-id="@category.ID">O'chirish</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="3" class="text-danger">Hech qanday savdo markazlari topilmadi.</td></tr>
            }
        </tbody>
    </table>
</div>

<script>

    $('#CategoryTable').DataTable();

    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '/Category/CategorySearch',
            data: {
                search: searchValue
            }
        })
        .done(function (response) {
            $("#tableContiner").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });


    $("#resetBtn").click(function () {
        var searchValue = '';

        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',//'/Category/CategoryTable',
            data: {
                search: searchValue
            }
        })
        .done(function (response) {
            $("#tableContiner").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });

    $("#newBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Category")',//'/Category/Create',
        })
        .done(function (response) {
            $("#actionContainer").html(response);

            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });


    $(".editBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Category")',
            data: {
                ID: $(this).attr('data-id')
            }
        })
        .done(function (response) {
            $("#actionContainer").html(response);

            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });


    @*$(".deleteBtn").click(function () {

        var confirmDelete = confirm("Are you sure you want to delete this category?");

        if (confirmDelete) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete", "Category")',
                data: {
                    ID: $(this).attr('data-id')
                }
            })
			.done(function (response) {
			    $("#tableContiner").html(response);
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
			    alert("FAIL");
			});
        }
    });*@

    $(".deleteBtn").click(function () {
        swal({
            title: "Tasdiqlash?",
            text: "Ushbu savdo markazini o'chirishga ishonchingiz komilmi?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Delete", "Category")',
                    data: {
                        ID: $(this).attr('data-id')
                    }
                })
                .done(function (response) {
                    $("#tableContiner").html(response);
                    swal("Muvaffaqiyatli o'chirildi.", {
                        icon: "success",
                    });
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });

            }
        });
    });
</script>

NewMarket.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";

}

<h2>Yangi savdo markazi yaratish </h2>

<form id="createCategory">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Nomi <span class="text-danger">*</span></label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Ta'rif</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Rasm</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Asosiymi?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" /> Ha</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" /> Yo'q</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>
    <button id="saveBtn" type="button" class="btn btn-primary">Saqlash</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Bekor qilish</button>
</form>
 
<script>

    $("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if(response.Success)
        	{
        		$("#ImageURL").val(response.ImageURL);
        		$("#categoryImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });


    $('#createCategory').validate({
        rules: {
            Name: {
                required: true,
                minlength: 5,
                maxlength: 50,
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            Name: {
                required: 'Nomi yozilishi shart',
                minlength: 'Minimum uzunligi 5',
                maxlength: 'Maksimum uzunigi 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            }
        }
    });

    $("#saveBtn").click(function () {
        debugger;
        if ($("#createCategory").valid()) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Category")',
                data: $("#createCategory").serialize()
            })
			.done(function (response) {
			    $("#tableContiner").html(response);
			    $("#actionContainer").html("");
			    focusAction("tableContiner");
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
			    swal({
			        title: "Diqqat",
			        text: "* bilan belgilangan barcha maydonlarni to'ldiring",
			        icon: "warning",
			        buttons: true,
			        dangerMode: true,
			    });
			});
        }
        else {
            swal({
                title: "Diqqat",
                text: "Barcha maydonlarni to'ldiring.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        focusAction("tableContiner");
    });
</script>

NewMarket.Web/Views/Category/Delete.cshtml
@model NewMarket.Entities.Category
@{
    ViewBag.Title = "O'chirish";
}

    <h2>Savdo markazini o'chirish</h2>

    <h1>Ushbu savdo markazini o'chirmoqchimisiz? </h1>

    <form method="post">
        <input type="hidden" name="ID" value="@Model.ID" />
        <button type="submit">Ha</button>
    </form>

    <a href="/Index">Bekor qilish</a>

NewMarket.Web/Views/Category/Edit.cshtml
@model NewMarket.Web.ViewModels.EditCategoryViewModels
@{
    ViewBag.Title = "O'zgartirish";

    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";

}

<h2>Savdo markazini o'zgartirish </h2>

<form id="editCategory">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Nomi</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Ta'rif</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Rasm</label>
                <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Asosiymi?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" @trueChecked /> Ha</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" @falseChecked /> Yo'q</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
            </div>
        </div>
    </div>
    <button id="updateBtn" type="button" class="btn btn-primary">O'zgartirish</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Bekor qilish</button>
</form>

<script>
    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);

            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#categoryImage").attr("src", response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });

    $("#updateBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Category")',
            data: $("#editCategory").serialize()
        })
        .done(function (response) {
            $("#tableContiner").html(response);
            $("#actionContainer").html("");
            focusAction("tableContiner");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
</script>

NewMarket.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Savdo markazlari";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Savdo markazlari 
                    </h2>
                </div>
            </div>
        </div>

        <div id="tableContiner">
            @{Html.RenderAction("CategoryTable");
            }
        </div>

        <hr />
        <div id="actionContainer">
        </div>
    </div>
</section>

<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
</script>