NewMarket.Web/Controllers/CategoryController.cs
using NewMarket.Entities;
using NewMarket.Services;
using System;
using NewMarket.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    //[Authorize(Roles ="Admin,Manager")]
    public class CategoryController : Controller
    {
        //CategoriesServices cs = new CategoriesServices();
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CategoryTable()
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            
            model.Categories = CategoriesServices.Instance.GetCategories();

            /*var categories = CategoriesServices.Instance.GetCategories();
            
            if (string.IsNullOrEmpty(search) == false)
            {
                categories = categories.Where(c => c.Name != null && c.Name.ToLower().Contains(search.ToLower())).ToList();
                categories = categories.Where(c => c.Name.Contains(search)).ToList(); 
            }*/
            return PartialView("CategoryTable", model);
        }

        public ActionResult CategorySearch(string search)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;

            var totalRecords = CategoriesServices.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesServices.Instance.GetCategoriesSearch(search);

            return PartialView("CategoryTable", model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            NewCategoryViewModels model = new NewCategoryViewModels();
            //var categories = CategoriesServices.Instance.GetCategories();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModels model)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesServices.Instance.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
 
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModels model = new EditCategoryViewModels();
            var category = CategoriesServices.Instance.GetCategory(ID);

            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Edit(EditCategoryViewModels model)
        {
            var existingCategory = CategoriesServices.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;

            CategoriesServices.Instance.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }

        
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            CategoriesServices.Instance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }
        
    }
}

NewMarket.Web/Controllers/ProductController.cs
using NewMarket.Entities;
using NewMarket.Services;
using NewMarket.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {          
            ProductSearchViewModel model = new ProductSearchViewModel();

            model.PageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            model.Products = ProductsService.Instance.GetProducts(model.PageNo);

            if (string.IsNullOrEmpty(search) == false)
            {
                model.SearchTerm = search;
                model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
                // products = products.Where(p => p.Name.Contains(search)).ToList();
            }
            return PartialView(model);

            //pageNo = pageNo.HasValue ? pageNo : 1;

            //var products = ProductsService.Instance.GetProducts(pageNo.Value);
            //if (string.IsNullOrEmpty(search) == false)
            //{
            //    products = products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            //    // products = products.Where(p => p.Name.Contains(search)).ToList();
            //}
            //return PartialView(products);

        }

        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoriesServices.Instance.GetCategories();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.Category = CategoriesServices.Instance.GetCategory(model.CategoryID);
            newProduct.ImageURL = model.ImageURL;

            ProductsService.Instance.SaveProduct(newProduct); 

            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductsService.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            //model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageURL = product.ImageURL;

            model.AvailableCategories = CategoriesServices.Instance.GetCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existringProduct = ProductsService.Instance.GetProduct(model.ID);
            existringProduct.Name = model.Name;
            existringProduct.Description = model.Description;
            existringProduct.Price = model.Price;
            existringProduct.Category = CategoriesServices.Instance.GetCategory(model.CategoryID);
            existringProduct.ImageURL = model.ImageURL;

            ProductsService.Instance.UpdateProduct(existringProduct);

            return RedirectToAction("ProductTable");
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.Instance.DeleteProduct(ID);

            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();
            model.Product = ProductsService.Instance.GetProduct(ID);
            return View(model);
        }
    }
}

NewMarket.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}",fileName) };

                //result.Data=new { Success=true,Image =fileName,File=newImage.ID,ImageURL=string.Format()}

            } catch (Exception e)
            {
                result.Data = new { Success = false, Message = e.Message };
            }

            return result;
        }
    }
}

NewMarket.Web/Controllers/ShopController.cs
using NewMarket.Services;
using NewMarket.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMarket.Web.Controllers
{
    public class ShopController : Controller
    {
       // ProductsService productsService = new ProductsService();
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel(); 

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if (CartProductsCookie != null)
            {
                //var ProductIDs = CartProductsCookie.Value;
                //var ids = ProductIDs.Split('-');
                //List<int> pIDs = ids.Select(x => int.Parse(x)).ToList();

                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsService.Instance.GetProducts(model.CartProductIDs);
            }

            return View(model);
        }
    }
}

NewMarket.Web/Views/Shared/_Layout.cshtml
﻿
<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title>SHOPpi </title>

    <meta name="author" content="themesflat.com">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/bootstrap.css">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/responsive.css">

    <!-- Colors -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/colors/color1.css" id="colors">

    <!-- Animation Style -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/animate.css">


    <!-- Favicon and touch icons  -->
    <link href="favicon.ico" rel="shortcut icon">

    <!--[if lt IE 9]>
        <script src="~/Content/javascript/html5shiv.js"></script>
        <script src="~/Content/javascript/respond.min.js"></script>
    <![endif]-->

    <script src="~/Content/javascript/jquery.min.js"></script>

</head>
<body class="header_sticky header-style-2 has-menu-extra">
    <!-- Preloader -->
    <div id="loading-overlay">
        <div class="loader"></div>
    </div>

    <!-- Boxed -->
   
    <div class="boxed">
    <div id="site-header-wrap">
        <!-- Header -->
        <header id="header" class="header clearfix">
            <div class="container-fluid clearfix container-width-93" id="site-header-inner">
                <div id="logo" class="logo float-left">
                    <a href="@Url.Action("Index","Home")" title="logo">
                        <img src="~/Content/images/login_logo.png" alt="image" width="107" height="24" data-retina="~/Content/images/login_logo.png" data-width="107" data-height="24">
                    </a>
                </div><!-- /.logo -->
                <div class="mobile-button"><span></span></div>
                <ul class="menu-extra">
                    <li class="box-search">
                        <a class="icon_search header-search-icon" href="#"></a>
                        <form role="search" method="get" class="header-search-form" action="#">
                            <input type="text" value="" name="s" class="header-search-field" placeholder="Izlash...">
                            <button type="submit" class="header-search-submit" title="Search">Izlash</button>
                        </form>
                    </li>
                    <li class="box-login">
                        <a class="icon_login" href="#"></a>
                    </li>
                    <li class="box-cart nav-top-cart-wrapper">
                        <a class="icon_cart nav-cart-trigger active" href="@Url.Action("Checkout", "Shop")"><span id="cartProductsCount">0</span></a>
                    </li>
                </ul><!-- /.menu-extra -->
                <div class="nav-wrap">
                    <nav id="mainnav" class="mainnav">
                        <ul class="menu">
                            <li>
                                <a href="@Url.Action("Index","Home")">Bosh sahifa </a>
                            </li>
                            <li class="active">
                                <a href="#">SHOPpi</a>
                                <ul class="submenu">
                                    <li>
                                        <a href="@Url.Action("Index","Category")">Savdo markazlari</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Product")">Mahsulotlar</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="coming-soon.html">SAHIFA</a>
                                <ul class="submenu">
                                    <li><a href="coming-soon.html">Tez kunda</a></li>
                                    <li><a href="404.html"> Error 404</a></li>
                                    <li><a href="faqs.html">FAQs</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="blog-list.html">BLOG</a>

                            </li>
                            <li>
                                <a href="contact.html">BIZ BILAN BOG'LANING</a>
                                <ul class="submenu right-submenu">
                                    <li><a href="contact.html">Contact Style 1</a></li>
                                    <li><a href="contact-v2.html">Contact Style 2</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav><!-- /.mainnav -->
                </div><!-- /.nav-wrap -->
            </div><!-- /.container-fluid -->
        </header><!-- /header -->
    </div><!-- /.site-header-wrap -->
    
        @RenderBody(); 
        @RenderSection("scripts", required: false)

    
    <section class="flat-row mail-chimp">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="text">
                        <h3>Obuna bo'lish</h3>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="subscribe clearfix">
                        <form action="#" method="post" accept-charset="utf-8" id="subscribe-form">
                            <div class="subscribe-content">
                                <div class="input">
                                    <input type="email" name="subscribe-email" placeholder="Emailingiz">
                                </div>
                                <div class="button">
                                    <button type="button">OBUNA BO'LISH</button>
                                </div>
                            </div>
                        </form>
                        <ul class="flat-social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul><!-- /.flat-social -->
                    </div><!-- /.subscribe -->
                </div>
            </div>
        </div>
    </section><!-- /.mail-chimp -->
        <!-- Footer --> 
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="widget widget-link">
                        <ul>
                            <li><a href="#">Biz haqimizda</a></li>
                            <li><a href="#">Onlayn do'kon</a></li>
                            <li><a href="blog-list.html">Blog</a></li>
                            <li><a href="contact.html">Biz bilan aloqa</a></li>
                        </ul>
                    </div><!-- /.widget -->
                </div><!-- /.col-md-3 -->
                <div class="col-md-3">
                    <div class="widget widget-link link-login">
                        <ul>
                            <li><a href="#">Ro'yxatdan o'tish</a></li>
                            <li><a href="#">Sizning savatchangiz</a></li>
                            <li><a href="#">Istaklar ro'yxati</a></li>
                        </ul>
                    </div><!-- /.widget -->
                </div><!-- /.col-md-3 -->
                <div class="col-md-3">
                    <div class="widget widget-link link-faq">
                        <ul>
                            <li><a href="faqs.html">FAQ</a></li>
                            <li><a href="#">Xizmatdan foydalanish shartlari</a></li>
                            <li><a href="#">Maxfiylik siyosati</a></li>
                        </ul>
                    </div><!-- /.widget -->
                </div><!-- /.col-md-3 -->
                <div class="col-md-3">
                    <div class="widget widget-brand">
                        <div class="logo logo-footer">
                            <a href="@Url.Action("Index","Home")"><img src="~/Content/images/login_logo.png" alt="image" width="107" height="24"></a>
                        </div>
                        <ul class="flat-contact">
                            <li class="address">O'zbekiston, Toshkent shahri</li>
                            <li class="phone">+99899 638-30-26</li>
                            <li class="email">infor.deercreative@gmail.com</li>
                        </ul><!-- /.flat-contact -->
                    </div><!-- /.widget -->
                </div><!-- /.col-md-3 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </footer><!-- /.footer -->

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright text-center">Mualliflik huquqi 2020 <a href="@Url.Action("Index","Home")">SHOPpi</a></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Go Top -->
        <a class="go-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
    
    <!-- Javascript -->
    <script src="~/Content/javascript/tether.min.js"></script>
    <script src="~/Content/javascript/bootstrap.min.js"></script>
    <script src="~/Content/javascript/jquery.easing.js"></script>
    <script src="~/Content/javascript/parallax.js"></script>
    <script src="~/Content/javascript/jquery-waypoints.js"></script>
    <script src="~/Content/javascript/jquery-countTo.js"></script>
    <script src="~/Content/javascript/jquery.countdown.js"></script>
    <script src="~/Content/javascript/jquery.flexslider-min.js"></script>
    <script src="~/Content/javascript/images-loaded.js"></script>
    <script src="~/Content/javascript/jquery.isotope.min.js"></script>
    <script src="~/Content/javascript/magnific.popup.min.js"></script>
    <script src="~/Content/javascript/jquery.hoverdir.js"></script>
    <script src="~/Content/javascript/owl.carousel.min.js"></script>
    <script src="~/Content/javascript/equalize.min.js"></script>
    <script src="~/Content/javascript/gmap3.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIEU6OT3xqCksCetQeNLIPps6-AYrhq-s&region=GB"></script>
    <script src="~/Content/javascript/jquery-ui.js"></script>

    <script src="~/Content/javascript/jquery.cookie.js"></script>
    <script src="~/Content/javascript/main.js"></script>

    <!-- Revolution Slider -->
    <script src="~/Content/rev-slider/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/rev-slider/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/Content/javascript/rev-slider.js"></script>
    <!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.video.min.js"></script>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</body>
</html>